package com.f14.TTA.consts

/**
 * 动画发生位置

 * @author 吹风奈奈
 */
enum class TTAAnimPosition {
    CURRENT_EVENT, LAST_EVENT, CARD_ROW, PLAYER_HAND, PLAYER_BOARD, UNUSED_WORKER, AVALABLE_BLUE, AVALABLE_YELLOW, UNCOMPLETE_WONDER, OUTGAME, SCIENCE, CULTURE, FUTURE_EVENT, SCIENCE_RATE, CULTURE_RATE, MILITARY, HAPINESS
}
