package com.f14.Eclipse.consts;

public enum TechnologyType {
    NEUTRON_BOMBS, STARBASE, PLASMA_CANNON, PHASE_SHIELD, ADVANCED_MINING, TACHYON_SOURCE, PLASMA_MISSILE, GLUON_COMPUTER, GAUSS_SHIELD, IMPROVED_HULL, FUSION_SOURCE, POSITRON_COMPUTER, ADVANCED_ECONOMY, TACHYON_DRIVE, ANTIMATTER_CANNON, QUANTUM_GRID, NANOROBOTS, FUSION_DRIVE, ADVANCED_ROBOTICS, ORBITAL, ADVANCED_LABS, MONOLITH, ARTIFACT_KEY, WORMHOLE_GENERATOR,

}
