package com.f14.f14bgdb.model

import com.f14.framework.common.model.BaseModel
import java.io.Serializable
import javax.persistence.*

/**
 * CodeDetailModel generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "CODE_DETAIL")
class CodeDetailModel : BaseModel(), Serializable {

    @get:Id
    @get:TableGenerator(name = "PK_GEN", allocationSize = 100, table = "PK_GEN", valueColumnName = "VALUE", pkColumnName = "NAME", pkColumnValue = "SEQ_ID")
    @get:GeneratedValue(strategy = GenerationType.TABLE, generator = "PK_GEN")
    @get:Column(name = "ID", unique = true, nullable = false)
    var id: Long? = null

    @get:Column(name = "CODE_TYPE")
    var codeType: String? = null

    @get:Column(name = "LABEL")
    var label: String? = null

    @get:Column(name = "VALUE")
    var value: String? = null

    @get:Column(name = "DESCR")
    var descr: String? = null

    @get:Column(name = "CODE_INDEX")
    var codeIndex: Int? = null

    @get:Column(name = "ACTIVE_IND")
    var activeInd: Boolean? = null

    companion object {
        private const val serialVersionUID = 1L
    }

}