package com.f14.machikoro.consts;

public enum MachiAbilityType {
    NONE, TWO_DICE, ENHANCE_INCOME, ONE_MORE_TURN, REROLL, INCOME_ALLTURN, INCOME_YOURTURN, INCOME_FROMPLAYER, EXCHANGE_BUILDING, TAKE_ONE, TAKE_OTHER,
}
